package bigTick.options;

public enum langs
{
	BTN_CLOSE,
	BTN_OPTIONS,
	BTN_BACK,
	BTN_APPLY,
	BTN_START,
	TAB_OPTIONS_GENERAL,
	TAB_OPTIONS_GRAFICS,
	TAB_OPTIONS_SOUNDS,
	TAB_OPTIONS_RESOURCES,
	NAME_OPTIONS_LANGUAGE,
	PLAYER_CHANGE,
	GAME_PLAYER_WON,
	GAME_PLAYER_LOSE,
	GAME_TIE;
}
